[[bin]]
name = "jwth"
path = "src/main.rs"
[package]
name = "jwt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"
hex = "0.4"
jsonwebtoken = "9.2"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
zeroize = "1.6"
rsa = "0.9"
p256 = { version = "0.13", features = ["pkcs8"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
pem = "3.0"
